CREATE TABLE IF NOT EXISTS brand (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(120) NOT NULL UNIQUE
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS model (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(120) NOT NULL,
  brand_id BIGINT NOT NULL,
  CONSTRAINT fk_model_brand FOREIGN KEY (brand_id) REFERENCES brand(id) ON DELETE RESTRICT,
  CONSTRAINT uq_model_brand_name UNIQUE (brand_id, name)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS vehicle (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  model_id BIGINT NOT NULL,
  year INT NOT NULL,
  color VARCHAR(60) NOT NULL,
  price DECIMAL(12,2) NOT NULL,
  mileage BIGINT NOT NULL,
  status VARCHAR(20) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_vehicle_model FOREIGN KEY (model_id) REFERENCES model(id) ON DELETE RESTRICT,
  INDEX idx_vehicle_status (status),
  INDEX idx_vehicle_year (year),
  INDEX idx_vehicle_price (price)
) ENGINE=InnoDB;


